services:
  postgresql:
    image: postgres:15.8-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Asia/Hong_Kong
      - PGTZ=Asia/Hong_Kong
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - shared
    restart: always

volumes:
  postgresql-data:
    driver: local
